# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# This workflow will do a clean installation of node dependencies, cache/restore them,
# build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v4  # Updated to v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4  # Updated to v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: cd platforms/electron; npm install

    - run: cd platforms/electron; npm run env-install

    - run: npm install

    - run: npm run install-all

    - run: npm run build

    - run: cd platforms/electron; npm run make-all --if-present

    - run: cd platforms/electron; cd ./out/make; npx tree-cli -l 4 -y

    - name: upload artifacts (Linux x64)
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: tiro-notes-linux-x64
        path: ./platforms/electron/out/make/deb/x64/*.deb

    - name: upload artifacts (Darwin ARM)
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: tiro-notes-darwin-arm
        path: ./platforms/electron/out/make/zip/darwin/arm64/*.zip

    - name: upload artifacts (Darwin x64)
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: tiro-notes-darwin-x64
        path: ./platforms/electron/out/make/zip/darwin/x64/*.zip

    - name: upload artifacts (Windows x64)
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: tiro-notes-win-x64
        path: ./platforms/electron/out/make/squirrel.windows/x64/*.exe